package sqlartan.core;

import sqlartan.core.stream.IterableStream;

/**
 * The structure interface for object generated by SQL queries.
 * This includes Results and Views.
 *
 * In addition to basic structures, these structures have a list of
 * sources used to generated them.
 *
 * @param <T> the actual type of the columns for this structure
 */
public interface QueryStructure<T extends GeneratedColumn> extends Structure<T> {
	/**
	 * Returns a list of sources used to generate this structure.
	 * Sources may not always be available.
	 */
	IterableStream<PersistentStructure<? extends Column>> sources();
}
